specVersion: 2
id: doc
title: DOCX Skill
description: Use when the task involves reading, creating, or editing `.docx`
  documents, especially when formatting or layout fidelity matters; prefer
  `python-docx` plus the bundled `scripts/render_docx.py` for visual checks.
category: tools
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/doc
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
