specVersion: 2
id: jupyter-notebook
title: Jupyter Notebook Skill
description: Use when the user asks to create, scaffold, or edit Jupyter
  notebooks (`.ipynb`) for experiments, explorations, or tutorials; prefer the
  bundled templates and run the helper script `new_notebook.py` to generate a
  clean starting notebook.
category: documentation
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/jupyter-notebook
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
