// site/lib/types.ts (v2)

export type I18nString = string | Record<string, string>;

export type RegistryIndex = {
  specVersion: number;
  generatedAt: string;
  skills: RegistrySkill[];
};

export type RegistryCategories = {
  specVersion: number;
  generatedAt: string;
  categories: RegistryCategory[];
};

export type RegistryCategory = {
  id: string;
  title: I18nString;
  description?: I18nString;
  icon?: string;
  order?: number;
};

export type RepositoryInfo = {
  url: string;
  owner: string;
  name: string;
  avatar?: string;
  stars?: number;
  forks?: number;
  updatedAt?: string;
};

export type RegistrySkill = {
  specVersion: number;
  id: string;
  title: string;
  description: I18nString;
  license?: string;
  authors?: Array<{ name: string; url?: string; email?: string }>;
  tags?: string[];
  agents?: string[];
  runtime?: string[];
  links?: { homepage?: string; docs?: string; repo?: string };
  source?: { repo?: string; path?: string; ref?: string; syncedCommit?: string };
  related?: string[];

  // Repository metadata
  repository?: RepositoryInfo;

  // Derived fields (generated by build-registry)
  category: string;  // v2: single category only
  repoPath: string;
  summary?: string;
  files?: Array<{ path: string; kind: "file" }>;
};
