specVersion: 2
id: notion-meeting-intelligence
title: Meeting Intelligence
description: Prepare meeting materials with Notion context and Codex research;
  use when gathering context, drafting agendas/pre-reads, and tailoring
  materials to attendees.
category: documentation
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/notion-meeting-intelligence
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
