specVersion: 2
id: openai-docs
title: OpenAI Docs
description: "Use when the user asks how to build with OpenAI products or APIs
  and needs up-to-date official documentation with citations (for example:
  Codex, Responses API, Chat Completions, Apps SDK, Agents SDK, Realtime, model
  capabilities or limits); prioritize OpenAI docs MCP tools and restrict any
  fallback browsing to official OpenAI domains."
category: documentation
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/openai-docs
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
