specVersion: 2
id: playwright
title: Playwright CLI Skill
description: Use when the task requires automating a real browser from the
  terminal (navigation, form filling, snapshots, screenshots, data extraction,
  UI-flow debugging) via `playwright-cli` or the bundled wrapper script.
category: tools
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/playwright
  ref: main
  syncedCommit: a5119697b819090e00e5d11ee1d86834d7c1043a
