specVersion: 2
id: ui-component-builder
title: UI Component Builder
description: Build beautiful UI components with AI assistance - supports React, Vue, and Svelte frameworks.
category: design
tags:
  - ui
  - components
  - react
  - vue
  - svelte
  - frontend
agents:
  - claude
  - cursor
runtime:
  - node
  - browser
license: Apache-2.0
source:
  repo: https://github.com/example/ui-component-builder
  path: skills/ui-builder
  ref: main
  syncedCommit: def789ghi012
