specVersion: 2
id: figma
title: Figma MCP
description: Use the Figma MCP server to fetch design context, screenshots,
  variables, and assets from Figma, and to translate Figma nodes into production
  code. Trigger when a task involves Figma URLs, node IDs, design-to-code
  implementation, or Figma MCP setup and troubleshooting.
category: design
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/figma
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
