specVersion: 2
id: pptx
title: PPTX creation, editing, and analysis
description: "Presentation creation, editing, and analysis. When Claude needs to
  work with presentations (.pptx files) for: (1) Creating new presentations, (2)
  Modifying or editing content, (3) Working with layouts, (4) Adding comments or
  speaker notes, or any other presentation tasks"
category: tools
source:
  repo: https://github.com/anthropics/skills
  path: skills/pptx
  ref: main
  syncedCommit: 1ed29a03dc852d30fa6ef2ca53a67dc2c2c2c563
