specVersion: 2
id: develop-web-game
title: Develop Web Game
description: "Use when Codex is building or iterating on a web game (HTML/JS)
  and needs a reliable development + testing loop: implement small changes, run
  a Playwright-based test script with short input bursts and intentional pauses,
  inspect screenshots/text, and review console errors with render_game_to_text."
category: development
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/develop-web-game
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
