specVersion: 2
id: pdf
title: PDF Skill
description: Use when tasks involve reading, creating, or reviewing PDF files
  where rendering and layout matter; prefer visual checks by rendering pages
  (Poppler) and use Python tools such as `reportlab`, `pdfplumber`, and `pypdf`
  for generation and extraction.
category: tools
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/pdf
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
