specVersion: 2
id: imagegen
title: Image Generation Skill
description: "Use when the user asks to generate or edit images via the OpenAI
  Image API (for example: generate image, edit/inpaint/mask, background removal
  or replacement, transparent background, product shots, concept art, covers, or
  batch variants); run the bundled CLI (`scripts/image_gen.py`) and require
  `OPENAI_API_KEY` for live calls."
category: tools
source:
  repo: https://github.com/openai/skills
  path: skills/.curated/imagegen
  ref: main
  syncedCommit: f46b2535abfc2ec4b383ba0da47a0357abfa198c
